server:
  port: 8080

spring:
  application:
    name: animal-character-analyzer-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

claude:
  api:
    key: ${CLAUDE_API_KEY:}
    url: https://api.anthropic.com/v1/messages

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.animalanalyzer: DEBUG
    org.springframework.web: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}