# Development profile configuration
cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:5174

logging:
  level:
    com.animalanalyzer: DEBUG
    org.springframework.web: DEBUG